version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - mysql
      - nginx

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3304:3306

  nginx:
    image: nginx:1.19.8-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 8084:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf:/etc/nginx/conf.d

volumes:
  db_data:
